/** Amptek Engineering — from Facebook page (cover + About) */
const AMPTEK = {
  name: 'Amptek Engineering',
  nameDisplay: 'AMPTEK ENGINEERING',
  shortName: 'Amptek',
  slogan: 'Engineering Tomorrow, Today!',
  tagline: 'Electrical, Fire Safety & Mechanical Solutions',
  taglineBn: 'ইলেকট্রিক্যাল, ফায়ার সেফটি ও মেকানিক্যাল সমাধান',
  pageType: 'Engineering Service',
  phone: '01671113615',
  phoneIntl: '+8801671113615',
  phoneDisplay: '01671-113615',
  email: 'info@amptekeng.com',
  emailAlt: 'nahidalam85@gmail.com',
  website: 'https://www.amptekeng.com',
  websiteDisplay: 'www.amptekeng.com',
  whatsapp: '8801671113615',
  facebook: 'https://www.facebook.com/AmptekEngineering',
  address: 'Holding No - 266, Rajabari Uttarkhan, Dhaka-1230, Bangladesh',
  addressShort: 'Rajabari Uttarkhan, Dhaka-1230',
  location: 'Dhaka, Bangladesh',
  hours: 'Sat–Thu: 9:00 AM – 6:00 PM',
  emergency: '24/7 Emergency Support',
  intro:
    'Amptek Engineering is a multi-discipline engineering service in Bangladesh — Power, Fire Safety, Mechanical, Industrial Automation and Safety Systems. Electrical, fire safety and mechanical solutions from design to commissioning.',
  mission:
    "Engineering tomorrow, today — delivering safe, efficient and compliant solutions that power industry and protect lives.",
  stats: [
    { num: '15+', label: 'Years Experience' },
    { num: '500+', label: 'Projects Completed' },
    { num: '50+', label: 'Certified Engineers' },
    { num: '5', label: 'Service Divisions' },
  ],
  clients: 'RMG factories, pharmaceutical plants, hospitals, data centres & commercial buildings',
  divisions: [
    { id: 'power', name: 'Power', icon: '⚡', desc: 'HT/LT Switchgear, BBT & Transformers' },
    { id: 'fire', name: 'Fire Safety', icon: '🔥', desc: 'NFPA Detection, Hydrants & FM-200' },
    { id: 'mechanical', name: 'Mechanical', icon: '⚙️', desc: 'Boiler, HVAC & Tank Fabrication' },
    { id: 'industrial', name: 'Industrial', icon: '🤖', desc: 'Automation, PLC & Machine Maintenance' },
    { id: 'safety', name: 'Safety', icon: '🛡️', desc: 'Lightning Protection & Compliance' },
  ],
};
