/** Amptek Engineering — from Facebook page (cover + About) */
const AMPTEK = {
  name: 'Amptek Engineering',
  nameDisplay: 'AMPTEK ENGINEERING',
  shortName: 'Amptek',
  slogan: 'Engineering Tomorrow, Today!',
  sloganBn: 'আজই আগামীর ইঞ্জিনিয়ারিং!',
  tagline: 'Electrical, Fire Safety & Mechanical Solutions',
  taglineBn: 'ইলেকট্রিক্যাল, ফায়ার সেফটি ও মেকানিক্যাল সমাধান',
  pageType: 'Engineering Service',
  phone: '01671113615',
  phoneIntl: '+8801671113615',
  phoneDisplay: '01671-113615',
  email: 'info@amptekeng.com',
  emailAlt: 'nahidalam85@gmail.com',
  website: 'https://www.amptekeng.com',
  websiteDisplay: 'www.amptekeng.com',
  whatsapp: '8801671113615',
  facebook: 'https://www.facebook.com/AmptekEngineering',
  address: 'Holding No - 266, Rajabari Uttarkhan, Dhaka-1230, Bangladesh',
  addressBn: 'হোল্ডিং নং - ২৬৬, রাজাবাড়ী উত্তরখান, ঢাকা-১২৩০, বাংলাদেশ',
  addressShort: 'Rajabari Uttarkhan, Dhaka-1230',
  location: 'Dhaka, Bangladesh',
  hours: 'Sat–Thu: 9:00 AM – 6:00 PM',
  hoursBn: 'শনি–বৃহস্পতি: সকাল ৯টা – সন্ধ্যা ৬টা',
  emergency: '24/7 Emergency Support',
  emergencyBn: '২৪/৭ জরুরি সহায়তা',
  intro:
    'Amptek Engineering is a multi-discipline engineering service in Bangladesh — Power, Fire Safety, Mechanical, Industrial Automation and Safety Systems. Electrical, fire safety and mechanical solutions from design to commissioning.',
  introBn:
    'অ্যাম্পটেক ইঞ্জিনিয়ারিং বাংলাদেশের একটি মাল্টি-ডিসিপ্লিন ইঞ্জিনিয়ারিং সেবা — পাওয়ার, ফায়ার সেফটি, মেকানিক্যাল, ইন্ডাস্ট্রিয়াল অটোমেশন ও সেফটি সিস্টেম। ডিজাইন থেকে কমিশনিং পর্যন্ত সম্পূর্ণ সমাধান।',
  stats: [
    { num: '15+', label: 'Years Experience', labelBn: 'বছরের অভিজ্ঞতা' },
    { num: '500+', label: 'Projects Completed', labelBn: 'প্রজেক্ট সম্পন্ন' },
    { num: '50+', label: 'Certified Engineers', labelBn: 'সার্টিফাইড ইঞ্জিনিয়ার' },
    { num: '5', label: 'Service Divisions', labelBn: 'সেবা বিভাগ' },
  ],
  divisions: [
    { id: 'power', name: 'Power Systems', nameBn: 'পাওয়ার সিস্টেম', icon: '⚡', desc: 'HT/LT Switchgear, BBT & Transformers', descBn: 'HT/LT সুইচগিয়ার, BBT ও ট্রান্সফরমার' },
    { id: 'fire', name: 'Fire Safety', nameBn: 'ফায়ার সেফটি', icon: '🔥', desc: 'NFPA Detection, Hydrants & FM-200', descBn: 'NFPA ডিটেকশন, হাইড্রান্ট ও FM-200' },
    { id: 'mechanical', name: 'Mechanical', nameBn: 'মেকানিক্যাল', icon: '⚙️', desc: 'Boiler, HVAC & Tank Fabrication', descBn: 'বয়লার, এইচভিএসি ও ট্যাংক ফ্যাব্রিকেশন' },
    { id: 'industrial', name: 'Industrial', nameBn: 'ইন্ডাস্ট্রিয়াল', icon: '🤖', desc: 'Automation, PLC & Maintenance', descBn: 'অটোমেশন, PLC ও মেইনটেন্যান্স' },
    { id: 'safety', name: 'Safety', nameBn: 'সেফটি', icon: '🛡️', desc: 'Lightning Protection & Compliance', descBn: 'লাইটনিং প্রটেকশন ও কমপ্লায়েন্স' },
  ],
};
